import { logger } from './logger'
import { GitCommit } from './types'

export type ExportFormat = 'markdown' | 'json' | 'html' | 'text'

export interface ChangelogData {
  version?: string
  date: string
  repository: string
  commits: GitCommit[]
  formattedChangelog: string
  startRef?: string
  endRef?: string
}

/**
 * Format date as readable string
 */
function formatDate(dateStr: string): string {
  const date = new Date(dateStr)
  return date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  })
}

/**
 * Export changelog as Markdown
 */
export function exportAsMarkdown(data: ChangelogData): string {
  logger.debug('Exporting changelog as Markdown')

  const version = data.version || 'Unreleased'
  const date = formatDate(data.date)
  const refRange = data.startRef && data.endRef ? `\n**Range:** \`${data.startRef}\` → \`${data.endRef}\`\n` : ''

  return `# Changelog - ${data.repository}

## ${version} - ${date}
${refRange}
${data.formattedChangelog}

---

### Commits (${data.commits.length})

${data.commits
  .map(
    (commit) =>
      `- **${commit.message.split('\n')[0]}**\n  _by ${commit.author.name}_ • ${formatDate(commit.author.date)} • \`${commit.sha.slice(0, 7)}\``
  )
  .join('\n\n')}

---
_Generated by GitString on ${formatDate(new Date().toISOString())}_
`
}

/**
 * Export changelog as JSON
 */
export function exportAsJSON(data: ChangelogData): string {
  logger.debug('Exporting changelog as JSON')

  return JSON.stringify(
    {
      version: data.version || 'Unreleased',
      date: data.date,
      repository: data.repository,
      startRef: data.startRef,
      endRef: data.endRef,
      changelog: data.formattedChangelog,
      commits: data.commits.map((commit) => ({
        sha: commit.sha,
        message: commit.message,
        author: {
          name: commit.author.name,
          email: commit.author.email,
          date: commit.author.date,
        },
        url: commit.url,
        stats: commit.stats,
        files: commit.files?.map(f => ({
          filename: f.filename,
          status: f.status,
          additions: f.additions,
          deletions: f.deletions,
        })),
      })),
      generatedAt: new Date().toISOString(),
      generatedBy: 'GitString',
    },
    null,
    2
  )
}

/**
 * Export changelog as HTML
 */
export function exportAsHTML(data: ChangelogData): string {
  logger.debug('Exporting changelog as HTML')

  const version = data.version || 'Unreleased'
  const date = formatDate(data.date)
  const refRange = data.startRef && data.endRef 
    ? `<div class="meta-item"><strong>Range:</strong> <code>${data.startRef}</code> → <code>${data.endRef}</code></div>` 
    : ''

  // Convert markdown changelog to HTML-safe version
  const changelogHtml = data.formattedChangelog
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\n/g, '<br>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/`(.*?)`/g, '<code>$1</code>')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Changelog - ${data.repository}</title>
  <style>
    * { box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      line-height: 1.6;
      max-width: 900px;
      margin: 0 auto;
      padding: 40px 20px;
      color: #1f2937;
      background: #f9fafb;
    }
    .container {
      background: white;
      padding: 40px;
      border-radius: 12px;
      box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
    }
    h1 {
      color: #2563eb;
      border-bottom: 3px solid #2563eb;
      padding-bottom: 12px;
      margin-top: 0;
      font-size: 2em;
    }
    h2 {
      color: #1e40af;
      margin-top: 30px;
      font-size: 1.5em;
    }
    .meta {
      display: flex;
      flex-wrap: wrap;
      gap: 20px;
      color: #6b7280;
      font-size: 0.95em;
      margin: 20px 0;
      padding: 15px;
      background: #f3f4f6;
      border-radius: 8px;
    }
    .meta-item { display: flex; gap: 8px; }
    .changelog {
      background: #f9fafb;
      padding: 24px;
      border-radius: 8px;
      border-left: 4px solid #2563eb;
      margin: 20px 0;
      font-size: 0.95em;
    }
    .commits {
      margin-top: 30px;
    }
    .commit {
      background: #fafafa;
      padding: 18px;
      margin: 12px 0;
      border-radius: 8px;
      border: 1px solid #e5e7eb;
      transition: all 0.2s;
    }
    .commit:hover {
      border-color: #2563eb;
      box-shadow: 0 2px 8px rgba(37, 99, 235, 0.1);
    }
    .commit-message {
      font-weight: 600;
      color: #1f2937;
      margin-bottom: 8px;
    }
    .commit-meta {
      color: #6b7280;
      font-size: 0.875em;
      display: flex;
      flex-wrap: wrap;
      gap: 12px;
    }
    .sha {
      font-family: 'Courier New', Courier, monospace;
      background: #e5e7eb;
      padding: 3px 8px;
      border-radius: 4px;
      font-size: 0.9em;
      color: #374151;
    }
    code {
      background: #f3f4f6;
      padding: 2px 6px;
      border-radius: 3px;
      font-size: 0.9em;
      font-family: 'Courier New', Courier, monospace;
    }
    footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 2px solid #e5e7eb;
      text-align: center;
      color: #9ca3af;
      font-size: 0.875em;
    }
    @media print {
      body { background: white; }
      .container { box-shadow: none; }
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Changelog - ${data.repository}</h1>
    
    <div class="meta">
      <div class="meta-item"><strong>Version:</strong> ${version}</div>
      <div class="meta-item"><strong>Date:</strong> ${date}</div>
      <div class="meta-item"><strong>Commits:</strong> ${data.commits.length}</div>
      ${refRange}
    </div>

    <h2>📝 Changes</h2>
    <div class="changelog">${changelogHtml}</div>

    <h2>📋 Commit Details</h2>
    <div class="commits">
      ${data.commits
        .map(
          (commit) => `
      <div class="commit">
        <div class="commit-message">${commit.message.split('\n')[0]}</div>
        <div class="commit-meta">
          <span>👤 ${commit.author.name}</span>
          <span>📅 ${formatDate(commit.author.date)}</span>
          <span class="sha">${commit.sha.slice(0, 7)}</span>
        </div>
      </div>`
        )
        .join('')}
    </div>

    <footer>
      Generated by <strong>GitString</strong> on ${formatDate(new Date().toISOString())}
    </footer>
  </div>
</body>
</html>`
}

/**
 * Export changelog as plain text
 */
export function exportAsText(data: ChangelogData): string {
  logger.debug('Exporting changelog as plain text')

  const version = data.version || 'Unreleased'
  const date = formatDate(data.date)
  const refRange = data.startRef && data.endRef ? `Range: ${data.startRef} → ${data.endRef}\n` : ''
  const separator = '='.repeat(80)

  // Strip markdown formatting from changelog
  const plainChangelog = data.formattedChangelog
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`(.*?)`/g, '$1')
    .replace(/#{1,6}\s/g, '')

  return `${separator}
CHANGELOG - ${data.repository}
${separator}

Version: ${version}
Date: ${date}
${refRange}Commits: ${data.commits.length}

${separator}
CHANGES
${separator}

${plainChangelog}

${separator}
COMMIT DETAILS
${separator}

${data.commits
  .map(
    (commit, index) =>
      `${index + 1}. ${commit.message.split('\n')[0]}
   Author: ${commit.author.name} <${commit.author.email}>
   Date: ${formatDate(commit.author.date)}
   SHA: ${commit.sha.slice(0, 7)}`
  )
  .join('\n\n')}

${separator}
Generated by GitString on ${formatDate(new Date().toISOString())}
${separator}
`
}

/**
 * Export changelog in the specified format
 */
export function exportChangelog(data: ChangelogData, format: ExportFormat): string {
  const startTime = Date.now()
  logger.info('Exporting changelog', { format, repository: data.repository, commitCount: data.commits.length })

  let result: string
  
  switch (format) {
    case 'markdown':
      result = exportAsMarkdown(data)
      break
    case 'json':
      result = exportAsJSON(data)
      break
    case 'html':
      result = exportAsHTML(data)
      break
    case 'text':
      result = exportAsText(data)
      break
    default:
      throw new Error(`Unsupported export format: ${format}`)
  }

  const duration = Date.now() - startTime
  logger.performance('exportChangelog', duration, { format, size: result.length })

  return result
}

/**
 * Get MIME type for export format
 */
export function getMimeType(format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return 'text/markdown'
    case 'json':
      return 'application/json'
    case 'html':
      return 'text/html'
    case 'text':
      return 'text/plain'
    default:
      return 'application/octet-stream'
  }
}

/**
 * Get file extension for export format
 */
export function getFileExtension(format: ExportFormat): string {
  switch (format) {
    case 'markdown':
      return 'md'
    case 'json':
      return 'json'
    case 'html':
      return 'html'
    case 'text':
      return 'txt'
    default:
      return 'txt'
  }
}
